INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,DIRECCION,CONTACTO,TIENDA_ID)
VALUES (1,'MIGUEL','PUEBLA CENTRO',1234567890,1);

INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,DIRECCION,CONTACTO,TIENDA_ID)
VALUES (2,'ROSA','TLAXCALA CENTRO',1234567890,2);

INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,DIRECCION,CONTACTO,TIENDA_ID)
VALUES (3,'EDUARDO','CDMX CENTRO',1234567890,3);

INSERT INTO CLIENTES (ID_CLIENTE,NOMBRE,DIRECCION,CONTACTO,TIENDA_ID)
VALUES (4,'TOMAS','CANCUN CENTRO',1234567890,4);

